version: "3"
services:
  google-sheet-service:
    container_name: google-sheet-container
    restart: always
    image: google-sheet-image:latest
    volumes:
      - .:/sheet-export
    environment:
      - MONGODB_URI=${mongodb_uri}
    command: python3 -u sync.py
    