version: '3'
services:
  telegram-bot:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/bot
    environment:
      - AGRIWEATHBOT_TOKEN=${agriweath_token}
    # ports:
    #   - 8000:8000
    command: python3 -u main.py
