version: '3'
services:
  telegram-bot:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/bot
    environment:
      - SECRET_AGRIWEATHBOT_TOKEN=${AGRIWEATHBOT_TOKEN}
    # ports:
    #   - 8000:8000
    command: python3 -u main.py
