version: "3"
services:
  telegram-bot:
    container_name: agri_weath_bot
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/bot
    environment:
      - AGRIWEATHBOT_TOKEN=${agriweath_token}
      - MONGODB_URI=${mongodb_uri}
      - ASANAK_USERNAME=${asanak_username}
      - ASANAK_PASSWORD=${asanak_password}
      - ASANAK_PHONE_NUM=${asanak_phone_num}
      - DB_NAME=${db_name}
      - DB_USER=${db_user}
      - DB_PASSWORD=${db_password}
      - DB_HOST=${db_host}
      - DB_PORT=${db_port}
    # ports:
    #   - 8000:8000
    command: python3 -u src/main.py
    networks:
      - abaad_network
    
networks:
  abaad_network:
    external:
      name: abaad-web-app_default