version: "3"
services:
  sms-service:
    container_name: sms-container
    restart: never
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/sms
    environment:
      - MONGODB_URI=${mongodb_uri}
      - ASANAK_USERNAME=${asanak_username}
      - ASANAK_PASSWORD=${asanak_password}
      - ASANAK_PHONE_NUM=${asanak_phone_num}
      - DB_NAME=${db_name}
      - DB_USER=${db_user}
      - DB_PASSWORD=${db_password}
      - DB_HOST=${db_host}
      - DB_PORT=${db_port}
    # ports:
    #   - 8000:8000
    # command: python3 -u src/main.py
    networks:
      - sms_network
    
networks:
  sms_network:
    external:
      name: abaad-web-app_default