name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-main-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: create requirements
        run: poetry export --without-hashes --format=requirements.txt > requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_NAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}

      # - name: Establish VPN connection
      #   run: |
      #       sudo apt update
      #       sudo apt install -y openvpn openvpn-systemd-resolved
      #       echo "${{ secrets.VPN_CONFIG }}" > vpn-config.ovpn
      #       echo "${{ secrets.VPN_USERNAME }}" > vpn-credentials.txt
      #       echo "${{ secrets.VPN_PASSWORD }}" >> vpn-credentials.txt
      #       sudo openvpn --config vpn-config.ovpn --auth-user-pass vpn-credentials.txt --daemon
      #       sleep 15
        
      - name: Deploy to Staging
        uses: appleboy/ssh-action@v0.1.10        
        with:
          host: ${{ secrets.PA_VPS_HOST }}
          username: ${{ secrets.PA_VPS_USERNAME }}
          password: ${{ secrets.PA_VPS_PASSWORD }}   
          port: ${{ secrets.PA_VPS_PORT }}
          script: |
            pwd
            cd telegram-bot
            docker-compose down
            sleep 15
            git fetch
            git pull 
            echo "FINSISHED UPDATING REPO"
            ls -lh
            docker-compose restart 
            sleep 15
